
[functions.start-practice]
enabled = true
verify_jwt = false
entrypoint = "./functions/start-practice/index.ts"

[functions.submit-practice]
enabled = true
verify_jwt = false
entrypoint = "./functions/submit-practice/index.ts"
